baseurl = "https://hark-project.net"
languageCode = "en-us"
title = "hark"
theme = "hark"
googleAnalytics = "UA-81656661-1"
pygmentsuseclasses = true

[params]
github = "https://github.com/hark-project"
twitter = "https://twitter.com/ceralena"

[[menu.main]]
	name = "about"
	identifier = "about"
	weight = 1
	url = "/about/"
[[menu.main]]
	name = "usage"
	identifier = "usage"
	weight = 2
	url = "/usage/"
[[menu.main]]
	name = "blog"
	identifier = "blog"
	weight = 3
	url = "/blog/"
[[menu.main]]
	name = "contribute"
	identifier = "contribute"
	weight = 4
	url = "/contribute/"

[[menu.about]]
	name = "index"
	identifier = "index"
	weight = 1
	url = "/about/"
[[menu.about]]
	name = "project status"
	identifier = "project status"
	weight = 2
	url = "/about/project_status/"
